#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$application = new Application();

// ... register commands
$application->add(new \TelegramApiParser\ParserDocumentation\Console\ParseCommand);
$application->add(new \TelegramApiParser\CodeGenerator\Console\GenerateClassesCommand);

$application->run();