#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new \TelegramApiParser\Console\ParseCommand);
$application->add(new \TelegramApiParser\Console\GenerateClassesCommand);

$application->run();